{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clustereye-api.fullname" . }}-secrets
  labels:
    {{- include "clustereye-api.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.global.secrets.jwtSecretKey | b64enc | quote }}
  API_SECRET_KEY: {{ .Values.global.secrets.apiSecretKey | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.global.secrets.encryptionKey | b64enc | quote }}
  DB_PASSWORD: {{ or .Values.global.database.password .Values.config.database.password | b64enc | quote }}
  {{- if .Values.global.externalInfluxDB.enabled }}
  INFLUX_TOKEN: {{ .Values.global.externalInfluxDB.token | b64enc | quote }}
  {{- else }}
  INFLUX_TOKEN: {{ or .Values.global.influxdb.token .Values.config.influxdb.token | b64enc | quote }}
  {{- end }}
{{- end }}