apiVersion: v1
kind: Service
metadata:
  name: {{ include "clustereye-envoy.fullname" . }}
  labels:
    {{- include "clustereye-envoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.envoy.service.type }}
  ports:
  - port: {{ .Values.envoy.service.port }}
    targetPort: {{ .Values.envoy.service.targetPort }}
    protocol: TCP
    name: http
  - port: 443
    targetPort: 10443
    protocol: TCP
    name: https
  selector:
    {{- include "clustereye-envoy.selectorLabels" . | nindent 4 }}