apiVersion: v1
appVersion: 2.7
description: Scalable datastore for metrics, events, and real-time analytics.
home: https://www.influxdata.com/time-series-platform/influxdb/
keywords:
- influxdb
- database
- timeseries
- influxdata
maintainers:
- email: johnblack@cloudnativeworks.com
  name: johnblack
- email: johnbrown@cloudnativeworks.com
  name: johnbrown
name: influxdb
sources:
- https://github.com/influxdata/influxdb
version: 4.12.5
