apiVersion: v2
name: clustereye-envoy
description: A Helm chart for Envoy proxy for ClusterEye stack
type: application
version: 0.1.0
appVersion: "1.31.0"
home: https://github.com/senbaris/clustereye
sources:
  - https://github.com/senbaris/clustereye
maintainers:
  - name: ClusterEye Team
keywords:
  - proxy
  - envoy
  - load-balancer
  - ingress